{"uuid": "a37320a4-edba-4c9e-a4ee-c1487acade40", "children": ["dc545c2a-d5b3-4a03-baca-cc2436d7e295"], "befores": [{"name": "add_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test_add_user' object has no attribute 'po'\n", "trace": "  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Iron men\\PycharmProjects\\pytest_ps\\scripts\\test_add_user.py\", line 29, in add_user\n    self.po.click_find_user()\n"}, "start": 1600849017380, "stop": 1600849017380}], "start": 1600849017380, "stop": 1600849017391}