{"uuid": "d9266f94-0bd2-4149-8e1f-3c00489531ca", "children": ["4a32ce2b-54d8-47c0-88bd-398768496b1a", "35887a28-6849-41ba-becd-8843010a56d9", "6b01685e-88bc-4087-9241-0c025ee38704", "0472200d-9e53-4edf-971a-74c1222ac248"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1600851529748, "stop": 1600851529749}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Test_add_user' has no attribute 'driver'\n", "trace": "  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\python.py\", line 749, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\python.py\", line 674, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\Iron men\\PycharmProjects\\pytest_ps\\scripts\\test_add_user.py\", line 24, in teardown_class\n    self.driver.quit()\n"}, "start": 1600851529935, "stop": 1600851529973}], "start": 1600851529748, "stop": 1600851529973}