{"uuid": "005f3d89-4faf-44fc-a6d4-7fc966f5b70c", "children": ["36cc88ca-0a37-4a41-bde2-be91759039d3"], "befores": [{"name": "add_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test_add_user' object has no attribute 'po'\n", "trace": "  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Iron men\\PycharmProjects\\pytest_ps\\scripts\\test_add_user.py\", line 29, in add_user\n    self.po.click_find_user()\n"}, "start": 1600849017398, "stop": 1600849017399}], "start": 1600849017398, "stop": 1600849017410}