{"uuid": "56f0b6a0-74cf-44d1-aaa1-de42b4727c90", "children": ["839c19fa-0e58-4732-abeb-94c535d6a742"], "befores": [{"name": "add_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test_add_user' object has no attribute 'add_user_obj'\n", "trace": "  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\iron men\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Iron men\\PycharmProjects\\pytest_ps\\scripts\\test_add_user.py\", line 29, in add_user\n    self.add_user_obj.click_find_user()\n"}, "start": 1600849318280, "stop": 1600849318281}], "start": 1600849318280, "stop": 1600849318365}