{"uuid": "5b4f8763-561b-42cd-8a13-9b763bbfe23e", "children": ["deee8475-c3ab-47f3-884a-9225d8f79748"], "befores": [{"name": "add_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test_add_user' object has no attribute 'add_user_obj'\n", "trace": "  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Iron men\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Iron men\\PycharmProjects\\pytest_ps\\scripts\\test_add_user.py\", line 29, in add_user\n    self.add_user_obj.click_find_user()\n"}, "start": 1600851455604, "stop": 1600851455604}], "start": 1600851455604, "stop": 1600851455622}